openapi: 3.0.3
info:
  title: BBang.Zip API
  version: 0.1.0
servers:
  - url: https://api.bbangzip.com
paths:
  /api/v1/auth/signup:
    post:
      summary: 회원가입
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [username, password, name, birthDate, gender, accountNumber, consent]
              properties:
                username: { type: string }
                password: { type: string }
                name: { type: string }
                birthDate: { type: string, format: date }
                gender: { type: string, enum: [MALE, FEMALE, OTHER] }
                accountNumber: { type: string }
                consent: { type: boolean }
      responses:
        '201': { description: created }
  /api/v1/auth/login:
    post:
      summary: 로그인
      responses:
        '200': { description: token issued }
  /api/v1/products:
    get:
      summary: 빵 목록 조회
      parameters:
        - in: query
          name: page
          schema: { type: integer, default: 0 }
        - in: query
          name: size
          schema: { type: integer, default: 20 }
        - in: query
          name: keyword
          schema: { type: string }
        - in: query
          name: region
          schema: { type: string }
        - in: query
          name: minRating
          schema: { type: number }
      responses:
        '200': { description: ok }
    post:
      summary: 빵 등록 (관리자)
      responses:
        '201': { description: created }
  /api/v1/products/{productId}:
    get:
      summary: 빵 상세
      parameters:
        - in: path
          name: productId
          required: true
          schema: { type: string }
      responses:
        '200': { description: ok }
        '404': { description: not found }
    patch:
      summary: 빵 수정 (가격 변경 시 버전 관리)
      responses:
        '200': { description: updated }
    delete:
      summary: 빵 삭제 (소프트 삭제)
      responses:
        '204': { description: deleted }
  /api/v1/orders:
    post:
      summary: 주문 생성
      responses:
        '201': { description: created }
  /api/v1/payments:
    post:
      summary: 결제 요청
      responses:
        '200': { description: paid }
  /api/v1/queue/enroll:
    post:
      summary: 대기열 등록
      responses:
        '201': { description: enrolled }
  /api/v1/queue/{queueId}:
    get:
      summary: 대기열 순번 조회
      parameters:
        - in: path
          name: queueId
          required: true
          schema: { type: string }
      responses:
        '200': { description: ok }
  /api/v1/queue/{queueId}/stream:
    get:
      summary: 대기열 실시간 스트림 (SSE)
      responses:
        '200': { description: stream }
